

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: produits
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080

  produit-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: produit-container
    restart: always
    ports:
        - 8088:8089
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/produits
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - postgres



volumes:
  postgres_data:
